#! /usr/bin/env bash

###################################################
#
#  Copyright (C) 2008-2013 Mario Kemper <mario.kemper@gmail.com>
#
#  This file is part of Shutter.
#
#  Shutter is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  Shutter is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Shutter; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
#
# In /usr/share/shutter/resources/system/plugins/shell/spdialogcrop/
# With .svg icon file
# Use Chrome or Chromium - 
# with options: Classic theme + Use system title bar and borders
# After new version of Chrome, check height of crop from top 
# There should be a tiny grey line around the screenshot
# Enter crop height in 2 places: BCROP and in convert statement
#
###################################################

TEXTDOMAIN=shutter-plugins
TEXTDOMAINDIR=$SHUTTER_INTL
PLUGIN_NAME=$"Dialogcrop"
PLUGIN_SORT=$"Tool"
PLUGIN_TIP=$"Crop an Abiquo screenshot to a dialog box"
PLUGIN_EXT="image/png;image/bmp;image/jpeg"

if [[ "${1}" = "name" ]];then
   	echo "${PLUGIN_NAME}"
    exit 0
elif [[ "${1}" = "sort" ]];then
    echo "${PLUGIN_SORT}"
    exit 0
elif [[ "${1}" = "tip" ]];then
    echo "${PLUGIN_TIP}"
    exit 0
elif [[ "${1}" = "ext" ]];then
    echo "${PLUGIN_EXT}"
    exit 0
fi

FILE="${1}"
WIDTH="${2}"
HEIGHT="${3}"
BCROP=$((HEIGHT-100))
#FILEYTPE="${4}"
#GEO="${2}x${3}"

#convert "${FILE}" -trim +repage "${FILE}"
convert "${FILE}" -crop "${WIDTH}"x"${BCROP}"+0+100 +repage \
 -fuzz 50% -trim +repage \
 -fuzz 50% -trim +repage "${FILE}"
exit 0
